fos_user:
  db_driver: orm # other valid values are 'mongodb' and 'couchdb'
  firewall_name: main
  user_class: App\Entity\User
  group:
    group_class: AppBundle\Entity\Group
  from_email:
    address: "walid.Asbaiti@gmail.com"
    sender_name: "walid.Asbaiti@gmail.com"
